
### 登录
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "edgex",
  "pwd": "edgex"
}

### 创建验证码
POST http://localhost:3000/auth

### 验证
GET http://localhost:3000/auth/validate-code?code=123456

### 获取验证码列表
GET  http://localhost:3000/auth?pageSize=10&pageNumb=1

### 获取最新验证码 废弃
GET http://localhost:3000/auth/newest-invite-code

